trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    py36:
      python.version: '3.6'
    py37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
  displayName: 'Install dependencies'

- script: |
    python -m pip install hpy-api/
    python -m pip install .
  displayName: 'Build project'

- script: |
    pip install pytest pytest-azurepipelines
    pytest --correct test/
  displayName: 'pytest'
