# Requirements for building the documentation with conda
name: hpydocs
dependencies:
  - python=3.7
  - sphinx=3.3.1
  - python-clang
  - pip:
    - sphinx-rtd-theme==0.5.0
    - sphinx-c-autodoc==0.3.1
