# Requirements for building the documentation with conda
name: hpydocs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - python-clang=10.0.1
  - pip:
    - sphinx==3.3.1
    - sphinx-rtd-theme==0.5.0
    - --nodeps sphinx-c-autodoc==0.3.1
    - beautifulsoup4
