# Requirements for building the documentation with conda
name: hpydocs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - llvm=11.0.0
  - clang=11.0.0
  - libclang=11.0.0
  - python-clang=11.0.0
  - pip:
    - sphinx==3.3.1
    - sphinx-rtd-theme==0.5.0
    - sphinx-c-autodoc==0.3.1
