on:
  workflow_call:
    inputs:
      portion:
        required: true
        type: string

jobs:
  valgrind_tests:
    # name: Valgrind tests
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Install / Upgrade system dependencies
        run: sudo apt update && sudo apt install -y valgrind

      - name: Install / Upgrade Python dependencies
        run: python -m pip install --upgrade pip wheel

      - name: Build
        run: python -m pip install .

      - name: Run tests
        env:
          HPY_TEST_PORTION: ${{ inputs.portion }}
        run: |
          python -m pip install pytest pytest-valgrind pytest-portion filelock
          make valgrind
